"""Services package — Auth, Project, Brief, PRD, AI services."""
from app.services.auth_service import (
    UserRegisterRequest,
    UserLoginRequest,
    TokenResponse,
    UserResponse,
    UserInDB,
    register_user,
    login_user,
    get_current_user_from_token,
    get_user_by_email,
    get_user_by_id,
    authenticate_user,
    create_access_token,
    decode_access_token,
    verify_password,
    get_password_hash,
)

from app.services.project_service import (
    ProjectCreateRequest,
    ProjectUpdateRequest,
    ProjectMemberRequest,
    ProjectResponse,
    ProjectListResponse,
    ProjectMemberResponse,
    create_project,
    get_project,
    get_project_response,
    list_projects,
    update_project,
    delete_project,
    is_project_owner,
    list_project_members,
    add_project_member,
    remove_project_member,
)

from app.services.brief_service import (
    BriefCreateRequest,
    BriefUpdateRequest,
    BriefApproveRequest,
    BriefResponse,
    BriefListResponse,
    BriefVersionSnapshot,
    create_brief,
    get_brief,
    get_brief_response,
    list_briefs,
    update_brief,
    delete_brief,
    transition_brief_status,
    submit_brief_for_review,
    approve_brief,
    reject_brief,
    create_new_version,
    list_brief_versions,
)

from app.services.prd_service import (
    PRDCreateRequest,
    PRDUpdateRequest,
    PRDApproveRequest,
    PRDResponse,
    PRDListResponse,
    PRDGenerateRequest,
    GenerateTasksRequest,
    TaskPreviewResponse,
    create_prd,
    get_prd,
    get_prd_response,
    list_prds,
    update_prd,
    delete_prd,
    approve_prd,
    generate_prd_from_brief,
    generate_tasks_from_prd,
    get_prd_tasks,
)

from app.services.ai_service import (
    GeneratedTask,
    PRDGenerationResult,
    TaskGenerationResult,
    ChatMessage,
    ChatCompletionResult,
    generate_prd_from_brief,
    generate_prd_from_brief_stream,
    generate_tasks_from_prd,
    chat_completion,
    check_ai_health,
)

__all__ = [
    # Auth
    "UserRegisterRequest",
    "UserLoginRequest",
    "TokenResponse",
    "UserResponse",
    "UserInDB",
    "register_user",
    "login_user",
    "get_current_user_from_token",
    "get_user_by_email",
    "get_user_by_id",
    "authenticate_user",
    "create_access_token",
    "decode_access_token",
    "verify_password",
    "get_password_hash",
    # Project
    "ProjectCreateRequest",
    "ProjectUpdateRequest",
    "ProjectMemberRequest",
    "ProjectResponse",
    "ProjectListResponse",
    "ProjectMemberResponse",
    "create_project",
    "get_project",
    "get_project_response",
    "list_projects",
    "update_project",
    "delete_project",
    "is_project_owner",
    "list_project_members",
    "add_project_member",
    "remove_project_member",
    # Brief
    "BriefCreateRequest",
    "BriefUpdateRequest",
    "BriefApproveRequest",
    "BriefResponse",
    "BriefListResponse",
    "BriefVersionSnapshot",
    "create_brief",
    "get_brief",
    "get_brief_response",
    "list_briefs",
    "update_brief",
    "delete_brief",
    "transition_brief_status",
    "submit_brief_for_review",
    "approve_brief",
    "reject_brief",
    "create_new_version",
    "list_brief_versions",
    # PRD
    "PRDCreateRequest",
    "PRDUpdateRequest",
    "PRDApproveRequest",
    "PRDResponse",
    "PRDListResponse",
    "PRDGenerateRequest",
    "GenerateTasksRequest",
    "TaskPreviewResponse",
    "create_prd",
    "get_prd",
    "get_prd_response",
    "list_prds",
    "update_prd",
    "delete_prd",
    "approve_prd",
    "generate_prd_from_brief",
    "generate_tasks_from_prd",
    "get_prd_tasks",
    # AI
    "GeneratedTask",
    "PRDGenerationResult",
    "TaskGenerationResult",
    "ChatMessage",
    "ChatCompletionResult",
    "generate_prd_from_brief",
    "generate_prd_from_brief_stream",
    "generate_tasks_from_prd",
    "chat_completion",
    "check_ai_health",
]
